--
-- PostgreSQL database dump
--

-- Started on 2011-04-16 12:01:47

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = off;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;

SET search_path = public, pg_catalog;

--
-- TOC entry 2749 (class 0 OID 17519)
-- Dependencies: 2210
-- Data for Name: dbprocessos_academicos; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (24, '10005348-948', '14303-1', '0000', 'Integralização Curricular', 'É a conclusão e a aprovação em todas as disciplinas e atividades previstas na organização curricular expresso no Projeto Pedagógico do curso.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (1, '10005325-925', '14303-1', '0000', 'Revisão de Avaliação Final', 'A solicitação de Revisão de Avaliação Final é regulamentada pela Resolução CÂM-EN no. 03/91, e com exceção dos Cursos que possuem Resolução própria, o pedido deverá ser realizado no prazo de até 48 horas úteis, após a data de publicação do resultado da avaliação final. O não preenchimento deste requisito implicará no indeferimento do requerimento.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (2, '10005326-926', '14303-1', '0000', 'Retorno', 'É a possibilidade de obtenção de vaga por ex-alunos da Universidade que tenham abandonado ou desistido do curso.

O retorno é realizado para o mesmo curso e para o currículo em vigor no semestre para o qual foi definido o retorno.

Para maiores informações acesse o Portal da Universidade no menu Informações Acadêmicas/Retorno.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (3, '10005327-927', '14303-1', '0000', 'Revisão de Avaliação', 'A solicitação de Revisão de Avaliação é regulamentada pela Resolução CÂM-EN no. 03/91 e, com exceção dos Cursos que possuem Resolução própria, o pedido deverá ser realizado no prazo de até 48 horas úteis, após a data de publicação do resultado da avaliação. O não preenchimento deste requisito implicará no indeferimento do requerimento.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (7, '10005331-931', '14303-1', '0000', 'Apostilamento de Diploma', 'O apostilamento de diploma consiste no acréscimo ou alteração de informação constantes no diploma, mediante averbação no verso do mesmo.

O apostilamento de diploma poderá ocorrer nos seguintes casos:

Alteração comprovada do nome do aluno;
Correção do número do RG;
Conclusão de nova habilitação para determinados curso como Comunicação social (jornalismo, publicidade e propaganda ou cinema e vídeo), Letras (inglês, espanhol, italiano) e outros.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (9, '10005333-933', '14303-1', '0000', 'Atestado de Formado', 'É o documento que comprova a situação acadêmica do aluno que já integralizou o currículo e que já colou grau, atestando a data da cerimônia de outorga de grau e a fase em que se encontra o processo de emissão do diploma.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (10, '10005334-934', '14303-1', '0000', 'Atestado de Formando', 'É o documento que comprova a situação do aluno prestes a integralizar o curso, ou de aluno que, tendo já integralizado o currículo, ainda não tenha recebido a outorga de grau, embora com data já definida.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (13, '10005337-937', '14303-1', '0000', 'Avaliação Presencial 2ª Chamada', 'A solicitação de prova de 2ª chamada destina-se a alunos matriculados em cursos ou disciplinas a distância e que, por motivo justificado e comprovado, não puderam realizar a prova na data prevista pelo professor. Com exceção dos Cursos que possuem regulamentação própria, o pedido deverá ser realizado no prazo de até 48 horas úteis, após a data da prova.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (14, '10005338-938', '14303-1', '0000', 'Benefício', 'São vantagens disponibilizadas aos alunos, professores e funcionários que compõe a Universidade.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (15, '10005339-939', '14303-1', '0000', 'Boleto', 'É um título de cobrança pagável em qualquer agência bancária do território nacional durante o período no qual o título de cobrança ainda não venceu, ou seja, até a data de vencimento. Após o vencimento, o boleto só poderá ser pago no banco que o emitiu, salvo as regras estipuladas pela Instituição para não receber após a data de vencimento.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (44, '10005368-968', '14303-1', '0000', 'Segunda Via do Diploma', '', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (16, '10005340-940', '14303-1', '0000', 'Bolsas', 'São incentivos ao aluno para auxiliar nos custos dos seus estudos.

As bolsas oferecidas pela Universidade são: PROUNI, bolsa do artigo 170 - estudo e pesquisa, bolsa do artigo 171, bolsa em projetos de pesquisa (PUIC, PIBIC, PMUC), bolsa em projetos de extensão.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (18, '10005342-942', '14303-1', '0000', 'Crédito Acadêmico', 'É a unidade que corresponde a um conjunto de conteúdos e atividades exigidas para a integralização do curso. Cada crédito corresponde a 15 horas-aula.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (21, '10005345-945', '14303-1', '0000', 'ENEM', 'O ENEM é uma avaliação realizada pelo Ministério da Educação, e também mais uma forma de Ingresso na Universidade. Pode ser realizado por alunos concluintes ou egressos do ensino médio.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (26, '10005350-950', '14303-1', '0000', 'Licença Gestante', 'À gestante é oferecido o atendimento especial de Licença de Gestação. Conforme prevê a Lei no. 6.202, de 17/4/75 a partir do oitavo mês, a gestante tem direito a 90 dias de licença, ou seja, um mês antes do parto e dois após, comprovado mediante atestado médico.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (4, '10005328-928', '14303-1', '0000', 'Abandono de Curso', 'É a não-efetivação de matrícula pelo aluno para um novo período letivo ocasionando a desvinculação com o curso e com a Universidade. Será também considerado em situação de abandono o aluno que atingiu o limite permitido de períodos em trancamento e deixou de matricular-se no período letivo imediatamente subsequente.', NULL, '0', '2010-09-15', '1', '431');
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (27, '10005351-951', '14303-1', '0000', 'Licença Médica: Atestado Médico ou Odontológico', 'O regime adotado para os cursos presenciais é o da presença obrigatória, nos termos da lei. Assim, a falta às atividades acadêmicas em face de compromisso médico ou odontológico – agendado ou não – não abona as faltas, mas apenas as justifica. Se comunicado com antecedência, facultará ao docente a proposição de atividades pedagógicas compensatórias. Noutra hipótese, a falta permanecerá, sendo apenas justificada.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (28, '10005352-952', '14303-1', '0000', 'Matrícula de Aluno Ingressante', 'É a matrícula dos candidatos aprovados em processo seletivo. Deverá ser realizada atendendo à legislação vigente e às normas institucionais. A falta de um dos documentos estipulados no edital implicará a não-efetivação da matrícula, não cabendo recurso, nem lhe sendo facultada a matrícula condicional. ', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (5, '10005329-929', '14303-1', '0000', 'Abono de Faltas', 'Não há abono de faltas com exceção dos casos amparados pela Lei no 4.375/64, em seu artigo 60, parágrafo 4 e pelo Decreto Lei no 715/69 ou seja, militar convocado para manobra ou exercício de ato cívico.', NULL, '0', '2010-09-15', '9', '432');
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (12, '10005336-936', '14303-1', '0000', 'Atestado de Matrícula', 'É o documento que comprova a regularidade da matrícula do aluno no curso e na Instituição de Ensino.', NULL, '0', '2010-09-15', '9', '435');
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (29, '10005353-953', '14303-1', '0000', 'Matrícula de Processos', 'É a matrícula dos candidatos aprovados em processos de transferência interna e externa, reingresso, retorno, remanejamento de campus, troca de turno, destrancamento de matrícula e permanência para nova habilitação.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (30, '10005354-954', '14303-1', '0000', 'Migração de Currículo', 'É a transferência do aluno de um currículo já existente para um em implantação. Pode ser realizada somente mediante documento de anuência do aluno e de análise de aproveitamento de disciplinas, pelo coordenador do curso.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (31, '10005355-955', '14303-1', '0000', 'Pré-requisito', 'São as condições que o aluno deve necessariamente cumprir para que possa matricular-se em uma determinada disciplina ou atividade prevista no projeto do curso. A condição pode ser a aprovação em disciplina ou disciplinas, atividades ou exame de proficiência. É responsabilidade do aluno observar os pré-requisitos determinados no projeto pedagógico do curso.

O pedido será encaminhado para avaliação do Coordenador do Curso e caso seja deferido, a disciplina solicitada será incluída automaticamente, na matrícula do aluno.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (34, '10005358-958', '14303-1', '0000', 'Transferência Externa do Exterior', 'É a passagem do vínculo (matrícula) que o aluno tem com o estabelecimento de origem estrangeira, para um estabelecimento no Brasil.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (36, '10005360-960', '14303-1', '0000', 'Troca de Turno', 'É a transferência de um turno para o outro, dentro do mesmo campus ou unidade, quando o curso é oferecido em dois ou mais turnos distintos.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (37, '10005361-961', '14303-1', '0000', 'Prouni', 'Programa Universidade para todos foi criado pela MP. 213/2004 e institucionalizado pela Lei no 11.096, de 13 de janeiro de 2005, cuja finalidade é a concessão de bolsas de estudos integrais e parciais a estudantes de baixa renda para cursos de graduação e seqüenciais de formação específica, em instituições privadas de educação superior.

Para conhecer os procedimentos, visite o link do PROUNI no Portal Universidade.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (39, '10005363-963', '14303-1', '0000', 'Refinanciamento de Débitos', 'É regulamentado através de instrução normativa semestral que oferece condições para parcelamento de dívida de mensalidade do semestre corrente. As datas para refinanciamentos são divulgadas no decorrer de cada semestre no Informativo de Matrícula e no site da Universidade.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (40, '10005364-964', '14303-1', '0000', 'Reingresso', 'É a forma de ingresso destinada a portador de diploma de curso superior de graduação ou sequencial de formação específica para um novo curso ou habilitação.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (41, '10005365-965', '14303-1', '0000', 'Relevação de Perda de Prazo', 'Conforme Instrução Normativa PROAC n° 01/2002, a Relevação de Perda de Prazo se aplica a toda e qualquer espécie de solicitação para a qual esteja fixada data ou prazo limite para ingresso do pedido no protocolo da Universidade. Tem a finalidade de dar uma nova oportunidade ao aluno, de requerer a solicitação específica que deixou de cumprir, no prazo estabelecido em Calendário Acadêmico, Edital, Regulamento Interno ou por determinação da Universidade. A aceitação do requerimento de relevação de perda de prazo não garante ao aluno o deferimento de seu pedido específico. Na solicitação, o aluno deverá indicar o processo em que deixou de cumprir o prazo.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (19, '10005343-943', '14303-1', '0000', 'Desistência de Vaga', 'É a desvinculação total do aluno com o curso e a Instituição, protocolada pelo aluno ou seu representante legal. O aluno só pode solicitá-la caso não tenha, no semestre, concluído nenhuma disciplina em que tenha se matriculado.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (42, '10005366-966', '14303-1', '0000', 'Remanejamento de Campus', 'É a transferência do aluno entre os campi ou unidades de aluno da Universidade para curso idêntico àquele em que esteja regularmente matriculado. Pode dar-se nas seguintes situações:

Aluno regularmente matriculado;
Aluno com matricula trancada. Neste último caso, o remanejamento fica condicionado ao período de validade do trancamento de matrícula. Nas duas situações, o remanejamento fica condicionado à existência de vaga e à solicitação de requerimento no setor de atendimento ao aluno.
Maiores informações acesse o Portal da Universidade no menu Informações Acadêmicas/Remanejamento de Campus.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (45, '10005369-969', '14303-1', '0000', 'Semestre Letivo', 'É o período definido pela IES para distribuição das atividades acadêmicas de um curso durante o período de um semestre, representado por cem dias de trabalho escolar efetivo. Na Universidade, o semestre letivo tem duração de 20 semanas, excluído o período de avaliação final.

Confira a data inicial e final que compreende ao Semestre Letivo de cada ano no Portal Universidade no menu Informações Acadêmicas/Calendário Acadêmico.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (11, '10005335-935', '14303-1', '0000', 'Atestado de Frequência', 'É o documento que comprova a freqüência do aluno nas disciplinas em que estiver efetivamente matriculado e cursando.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (23, '10005347-947', '14303-1', '0000', 'Histórico Escolar', 'É o documento oficial que representa o desempenho acadêmico do aluno e contém o registro de todas as atividades acadêmicas previstas na organização curricular e resultados obtidos durante o seu vínculo com a Instituição de Ensino.', NULL, '0', '2010-09-15', '1', '439');
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (32, '10005356-956', '14303-1', '0000', 'Trancamento de Disciplina', 'É a desistência do aluno, com matrícula regular, de continuar cursando uma ou mais disciplinas.

A partir do trancamento da disciplina, o aluno está isento de pagar as parcelas vincendas, no entanto, não é restituído dos valores pagos.', NULL, '0', '2010-09-15', '9', NULL);
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (35, '10005359-959', '14303-1', '0000', 'Transferência Interna', 'É a transferência do aluno de um curso para outro, dentro da Universidade.', NULL, '0', '2010-09-15', '1', '472');
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (38, '10005362-962', '14303-1', '0000', 'Prova de Segunda Chamada', 'A solicitação de prova de 2ª chamada destina-se a alunos que, por motivo justificado e comprovado, não puderam realizar a prova na data prevista pelo professor. Com exceção dos Cursos que possuem regulamentação própria, o pedido deverá ser realizado no prazo de até 48 horas úteis, após a data da prova.', NULL, '0', '2010-09-15', '9', '441');
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (8, '10005332-932', '14303-1', '0000', 'Aproveitamento de Disciplina', 'É o resultado da análise de equivalência entre disciplinas cursadas em outros cursos da Universidade ou em outras Instituições de Ensino Superior (IES) e as disciplinas da matriz curricular do curso no qual o aluno está matriculado. Este processo objetiva o aproveitamento e validação das disciplinas já cursadas, com as do curso atual. Para serem consideradas equivalentes, a disciplina a ser aproveitada precisa corresponder em 75% do conteúdo e ter carga horária igual ou superior àquela que se quer validar.', NULL, '0', '2010-09-15', '1', '434');
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (47, '10010117-317', '14303-1', '0000', 'Regularização de Aluno Especial', 'Consiste na correção da grade de disciplinas do aluno.', NULL, '0', '2011-02-05', '1', '454');
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (6, '10005330-930', '14303-1', '0000', 'Revalidação de Diploma', 'Para ingresso em cursos superiores, os alunos formados no exterior, salvo em países com os quais o Brasil possui acordos, deverão ter seu diploma revalidado, conforme determina a legislação.', NULL, '0', '2010-09-15', '9', '433');
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (17, '10005341-941', '14303-1', '0000', 'Colação de Grau em Gabinete', 'Poderá ser outorgado o grau em data e local determinado pelo Reitor, ou por quem com delegação para tal e na presença de, no mínimo, dois professores, ao aluno formando que não puder receber o grau na sessão solene, por motivo justificado e devidamente comprovado, desde que formalmente solicitado.

Para a colação de grau, o aluno não poderá ter nenhuma pendência de documentos na Universidade.', NULL, '0', '2010-09-15', '9', '436');
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (25, '10005349-949', '14303-1', '0000', 'Justificativa de Faltas', 'É a situação em que o aluno, regularmente matriculado e amparado pela legislação (Lei 6.202/75), necessita de uma programação que possibilite a apreensão e compreensão dos conteúdos estabelecidos em técnicas e procedimentos especiais, adequados às peculiaridades dos casos e dos componentescurriculares. Pode ser também facultada aos alunos portadores de afecções congênitas ou adquiridas, traumatismos ou outras condições mórbidas que determinem incapacidade relativa, conforme lei 1044/69. A justificativa de faltas difere do abono de faltas', NULL, '0', '2010-09-15', '9', '440');
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (33, '10005357-957', '14303-1', '0000', 'Transferência Externa', 'É a transferência do vínculo do aluno de curso de graduação ou pós-graduação stricto sensu de um estabelecimento de origem para outro estabelecimento de destino.', NULL, '0', '2010-09-15', '1', '471');
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (22, '10005346-946', '14303-1', '0000', 'Guia de Transferência', 'E o documento oficial exigido e emitido pela Universidade e que transfere o vínculo do aluno com o curso para outra instituição de Ensino Superior para prosseguimento de seus estudos. Se o vínculo de matrícula não existir, a Guia de Transferência não poderá ser expedida.', NULL, '0', '2010-09-15', '9', '438');
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (43, '10005367-967', '14303-1', '0000', 'Ressarcimento para Desistência do Curso', 'É a possibilidade de resgatar 80% do valor pago referente a matrícula. A diferença é retida em função de despesas administrativas. Pode ser realizado até 1(um) dia útil antes do início das aulas.', NULL, '0', '2010-09-15', '9', '442');
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (20, '10005344-944', '14303-1', '0000', 'Reabertura de Matrícula', 'O destrancamento de matrícula é a solicitação formal da continuidade dos estudos de aluno com matrícula trancada. A solicitação de destrancamento de matrícula pode ser cumulada com solicitação de transferência interna, remanejamento de campus ou troca de turno, devendo o aluno, para tanto, realizar pedidos concomitantes.', NULL, '0', '2010-09-15', '1', '437');
INSERT INTO dbprocessos_academicos (id, codigo, unidade, codigoautor, titulo, procedimento, requisitos, alteratransacao, datacad, ativo, formulario) VALUES (46, '10005370-970', '14303-1', '0000', 'Trancamento de Curso', 'Consiste na interrupção temporária dos estudos, solicitado pelo aluno, através de requerimento.', NULL, '0', '2010-09-15', '1', '473');


-- Completed on 2011-04-16 12:01:47

--
-- PostgreSQL database dump complete
--

